### PR TITLE
Fix for youtube playlists, add bandcamp support, fix soundcloud playlists

### PR DESCRIPTION
**Pull request by Virusmater**
I developed bandcamp plugin (https://github.com/Virusmater/plugin.audio.kxmxpxtx.bandcamp), so added support to your beautiful tool.
In meanwhile I noticed that youtube playlists don't work anymore. Kodi wasn't opening anything at all. Url example:
https://www.youtube.com/watch?v=emGri7i8Y2Y&list=PL-aQd8Gsz8xcsUrW5t5bP7I2nfHoy42sP
and fixed it.
Also soundcloud playlist feature wasn't working as well. Only first song from the list was playing. Url example:
https://soundcloud.com/thiago-silva-394/sets/chill-out-2018
fixed it as well.

Tested it only with youtube single file, youtube playlist, soundcloud playlist, bandcamp playlist.
Hope I didn't break anything.

### CODE REVIEW

**Comment by regseb** [comment]
Hi,

Cast Kodi sends videos and music to the video player. This way you can listen to music from YouTube Music and SoundCoud in the same player.
If you play a `file` to `Player.Open`, Kodi will decide whether to send the media to the video or audio player. Sending a SoundCloud playlist doesn't work because the SoundCloud plugin [inserts all the music into the audio player](https://github.com/jaylinski/kodi-addon-soundcloud/blob/64e51f2bedb840a4ad00fa0f2926e699d6a2f5d6/resources/plugin.py#L107), while the media has been added to the video player. Maybe the plugin can insert the music in the same player as the source?

To YouTube, adding the `play=1` option is good. But don't put `order=default` to leave the choice to the user.
For Bandcamp, it's good to add it in Cast Kodi.
If you modify the pull request with only Bandcamp and `play=1` option of YouTube, I'll integrate it in the next release.

Thank you for your contribution.

**Comment by Virusmater** [comment]
I would prefer that default sorting method to be configurable on castkodi side then (ask, default, reverse, shuffle).
Use case:
There is a party at user's place. User adds few playlists from YouTube. And now every time when the playlist ends - the music suddenly stops and popup with "Select order of the playlist" appears. Now user has to find the remote or go back to PC in order to continue the music playing. And this will happen with every playlist that were added. Not good UX from my side. I think that really few people are using non-default order of the playlist anyway.

I run some tests and can say that your use case with mixed video/audio playlists doesn't work now anyway.
Current behavior:
Play now:
```
{"jsonrpc":"2.0","method":"Playlist.Clear","params":{"playlistid":1},"id":3}
{"jsonrpc":"2.0","method":"Playlist.Add","params":{"playlistid":1,"item":{"file":"plugin://*"}},"id":4}
{"jsonrpc":"2.0","method":"Player.Open","params":{"item":{"playlistid":1,"position":0}},"id":5}
```
Queue item:
```
{"jsonrpc":"2.0","method":"Playlist.Add","params":{"playlistid":1,"item":{"file":"plugin://*"}},"id":3}
```

Start from YouTube:
1. Play now from YouTube => YouTube starts play
2. Queue item from SoundCloud => Track got queued, next button is available
3. Click next in Kodi => Track from SoundCloud is playing
From now on queue is kinda screwed up
4. Queue item from SoundCloud => Next button in the player isn't available, but when previous SoundCloud track (from step 2) reaches the end - this track (from step4) starts. It has no info it all, only file name (no artist, no track, no art)
5. Queue item from YouTube => Next button in the player isn't available, but when SoundCloud track reaches the end - YouTube is starting, but only audio, no video
6. Queue item from SoundCloud => Next button in the player isn't available, but track starts and all info is displayed

PR behavior (actually the same as the current one):
Play now:
```
{"jsonrpc":"2.0","method":"Player.Open","params":{"item":{"file":"plugin://*"}},"id":3}
```
Queue item:
```
{"jsonrpc":"2.0","method":"Playlist.Add","params":{"playlistid":1,"item":{"file":"plugin://*"}},"id":3}
```

1. Play now from YouTube => YouTube starts play
2. Queue item from SoundCloud => Track got queued
3. Click next in Kodi => Track from SoundCloud is playing
4. Queue item from SoundCloud => Next button in the player isn't available, but when previous SoundCloud track (from step 2) reaches the end - this track (from step4) starts. It has no info it all, only file name (no artist, no track, no art)
5. Queue item from YouTube => Next button in the player isn't available, but when SoundCloud track reaches the end - YouTube is starting, but only audio, no video
6. Queue item from SoundCloud => Next button in the player isn't available, but track starts and all info is displayed

So I see no harm, only pros of having my approach. Do you have a counter example?

Having a support of Bandcamp plugin without Player.Open (File) makes no sense since everybody is listening music on Bandcamp by albums. This is the main feature of the service.

I think that the best we can do - call Player.GetActivePlayers before adding to the queue and route items to the currently active queue.

**Comment by Virusmater** [comment]
I think that I got your point. Currently there is "playerid: 1" is hardcoded everywhere in Cast Kodi. And currently if SoundCloud track was shared from Yatse (popular remote for Android) - then it wouldn't be possible to control Kodi playback with Cast Kodi.
I will look into dynamic playerid based on GetActivePlayers instead of hardcoded one.

**Comment by Virusmater** [comment]
Added a dynamic playerid feature. Now Cast Kodi works even if a song from SoundCloud or Bandcamp was started by Yatse. Wow!
Tested the following flow:

1. Play Bandcamp
2. Queue YouTube
3. Queue SoundCloud
4. Queue YouTube
5. Queue SoundCloud

And a playlist was played without any problems at all.

**Comment by regseb** [comment]
Cast Kodi sends everything to the video player because it is too complex to send to many players under certain conditions.

In your proposal, the media is added in the same player as the previous media. But if you queue item when there is no current player, the `getCurrentPlayerId` method fails because there is no current player.

If you play a YouTube video, then a SoundCloud playlist. The YouTube video will be in the video player, but the SoundCloud plugin will insert the music from the playlist into the audio player.

And you have the remote control to start the video player. If you have two players, it will not be which one to launch.

**Comment by Virusmater** [comment]
That's why if there is no an active media is playing and user added something to the playlist - it should start playing immediately. Otherwise it isn't possible to start using default/official Kodi ways.
Just tried to add YouTube video to the playlist with Cast Kodi and then somehow start it using TV Remote/Yatse/Keyboard/Mouse - nothing works.
This is how Kore/Yatse are working right now. I think this is kinda expected by user (myself included). So I addressed it in the commit 3b9f268 and 28a54e6
Also addressed your concern about playlist order for youtube lists - added new configuration setting in the commit 4353607

**Comment by andy5macht** [comment]
I would love to see this features to get merged.
Casting playlist to Kodi without getting asked for the playing order would be soo damn nice.

**Comment by regseb** [comment]
@andy5macht The option to set the order of Youtube playlists has been added in version _5.7.0_ of Cast Kodi (requires Firefox _84_).

**Pull request closed without merging**
