### PR TITLE
Add support for star tv videos.

### PR DESCRIPTION
**Pull request by godfath3r**
Hello,
js is not my language, so please be kind :) 
I took example from other scrapers, and its a simple regex match to find first m3u8 link. 
(I even left french comments intact, heh :D )

### CODE REVIEW

**Comment by godfath3r** [comment]
Finally I've fixed lint errors.

Integrations test are failing. Can you please instruct me how to debug? Is it possible my code broke those tests?
Also coverage is decreased, I could try to write some basic unit test, don't know where (and how) to start though.

**Comment by godfath3r** [comment]
@regseb Would you merge the changes?

**Comment by regseb** [comment]
Thank you for the proposal. I've added support for embedded YouTube videos (like [this one](https://www.star.gr/tv/psychagogia/ston-kosmo-tou/ston-kosmo-tou-2042019-tiflida/)) and integration testing.

Your pull request is published in the new version _5.11.0_ (requires Firefox _87+_).

**Comment by godfath3r** [comment]
That's great! Thank you.

**Pull request merged**
